### ISSUE TITLE
[FEAT] comment list 반환 수정

### ISSUE THREAD

**Issue by chhs2131** [chhs2131/dbsgAPI#59]
## 목적
> comment list 표현 방식을 게시글과 유사하게 변경하여, 가독성(정보파악)을 높이기 위함

<br/>

## 상세내용
- [x] comment의 `title` 항목에 문구를 간단한 범주로 수정
  1. 철회
      - 청약이 철회되었습니다.
  2. 신규로 등록된 것
      - 신규 등록되었습니다.
  3. 일정변경
      - 일정이 변경되었습니다.
  4. 공모관련 정보 변경 (확정가, 밴드, 수요예측경쟁률, 환매청구권,. …)
      - 공모 정보가 업데이트 되었습니다.
  5. 기업정보 변경 (매출액, 업종, … ) - 제외
      - 기업 정보가 업데이트 되었습니다.
  6. 주간사 관련 정보 변경 (청약가능 수량, 증거금 비율, 주간사 추가되는 경우?)
      - 배정수량이 변경되었습니다.

 - [x] #64
 - [x] Comment Enum 작성 (KindOfComment)
   - 형식 (소속, 내용)
 - [x] JsonCommentConverter의 `commentList` 의 구성 및 대입 값 수정
   - 기존 List<String>
   - 변경 List<KindOfComment, String>  : 별도의 데이터 클래스로 분리 필요
 - [x] `comment_list` 항목들을 상세하게 분리
   - 각 항목은 `type`, `comment`, `detail` 를 가지며, detail에 상세한 내용이 들어가게된다.

<br/>

### 반환 예시
- 기존 반환
```json
  {
    "commentIndex": 900,
    "ipoIndex": 153,
    "writer": "DB_TRIGGER",
    "stockName": "와이오엠",
    "stockKinds": "실권주",
    "comment": "대금 환불일이 변경되었습니다. (2022-12-29) - 외 1건",
    "commentList": [
      "대금 환불일이 변경되었습니다. (2022-12-29)",
      "구주주 청약일이 변경되었습니다. (2022-12-21 ~ 2022-12-22)"
    ],
    "registDate": "2022-10-28"
  },
```

- 변경된 반환
```json
  {
    "commentIndex": 900,
    "ipoIndex": 153,
    "writer": "DB_TRIGGER",
    "stockName": "와이오엠",
    "stockKinds": "실권주",
    "title": "일정이 변경되었습니다.",
    "commentList": [
      {
        "type": "SCHEDULE",
        "comment": "대금 환불일이 변경되었습니다.",
        "detail": "2022-12-29"
      },
      {
        "type": "SCHEDULE",
        "comment": "구주주 청약일이 변경되었습니다.",
        "detail": "2022-12-21 ~ 2022-12-22"
      }
    ],
    "registDate": "2022-10-28"
  },
```

**Comment by eugene-doobu** [comment]
commnet  오타있습니다

**Comment by chhs2131** [comment]
> commnet 오타있습니다

오우 감사합니다 ^_^
