### ISSUE TITLE
[FIX] Calendar 철회 종목 반환되지 않도록 수정

### ISSUE THREAD

**Issue by psw9999** [chhs2131/dbsgAPI#60]
## 목적
- Calendar에 청약 철회된 종목은 보여줄 필요가 없을 것 같아 수정이 필요할 것 같습니다~

## 상세내용
- [ ] Calendar API 청약 철회 종목은 데이터 반환하지 않도록 수정

**Comment by chhs2131** [comment]
#61  로 연계합니다~
